name: snakeobjectsDev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - ipython
  - setuptools
  - pytest-cov
  - sphinx
  - conda-build
  - anaconda-client
  - snakemake-minimal>5.20
  - sphinx_rtd_theme
  - mamba
  - pip
  - pip:
    - sphinx-autorun
