name: snakeobjectsGATKExample
channels:
  - iossifovlab 
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - snakeobjects
  - pandas
  - numpy
  - matplotlib
  - graphviz
  - bwakit
  - samtools 
  - pysam
  - gatk4


